@startuml
' API
package "API" #D5E1F9 {
  object ApiClient {
    - BASE_URL: String
    - CUSTOM_HEADERS: Map<String, String>
    - USERNAME: String
    - PASSWORD: String
    - getAuthorizationHeader(): String
    + create(): ApiService
  }

  interface ApiService {
    + getLecturerSchedule(idProgramStudi: RequestBody, idPeriode: RequestBody): ScheduleResponse
  }

  class CustomHeadersInterceptor {
    - headers: Map<String, String>
    - authorizationHeader: String
    + intercept(chain: Interceptor.Chain): Response
  }
}

@enduml